# Generated by Django 3.2.8 on 2021-10-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=100)),
                ('file_field', models.FileField(upload_to='C:/Users/khangtg/Desktop/nmail_comm/uploads')),
            ],
        ),
    ]
